import type {Data} from '../types';
import {addMonths,today} from './domain';
const id=(n:number)=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
export const defaults={id:1,name:'BALAJI ELECTRIC REPAIR AND SERVICES',address:'Shop No 2, Juhu Road, Andheri',phone1:'7021935696',phone2:'9769972070',gst_number:'',upi_id:'',review_url:'',footer:'Thank you for choosing Balaji Electric.',default_warranty:3};
export function seed():Data{
 const created_at=new Date().toISOString();
 const customers=['Asha Sharma','Rahul Verma','Priya Mehta','Imran Khan','Neha Patil'].map((name,i)=>({id:id(i+1),name,mobile:`900000000${i+1}`,address:['Andheri West','Juhu Road','Vile Parle','Andheri East','DN Nagar'][i]+', Mumbai',notes:'',tags:['demo'],whatsapp_opt_in:i!==2,opt_out:false,created_at}));
 const complaints=Array.from({length:8},(_,i)=>({id:id(i+101),number:`BE-${String(i+1).padStart(6,'0')}`,customer_id:customers[i%5].id,appliance:(['ac','washing','microwave','other'] as const)[i%4],brand:['LG','Samsung','Voltas',''][i%4],issue:['AC is not cooling.','Machine is making unusual noise.','Food is not heating.','Appliance is not turning on.'][i%4],status:(['pending','scheduled','in_progress','completed'] as const)[i%4],priority:i===0?'urgent':'normal',visit_at:i%4===1?created_at:null,technician_id:i%2===0?id(501):null,source:'walkin',internal_notes:'',created_at:new Date(Date.now()-(i%4)*86400000).toISOString(),updated_at:created_at,feedback_token:id(i+801)}));
 const inventory_items=[{id:id(601),name:'AC capacitor',category:'Capacitor',sku:'DEMO-CAP',purchase_price:250,selling_price:450,stock_quantity:8,low_stock_level:3,supplier:'Local supplier'},{id:id(602),name:'Washing motor',category:'Motor',sku:'DEMO-MOTOR',purchase_price:1400,selling_price:2200,stock_quantity:2,low_stock_level:3,supplier:'Local supplier'},{id:id(603),name:'Magnetron',category:'Microwave',sku:'DEMO-MAG',purchase_price:900,selling_price:1500,stock_quantity:5,low_stock_level:2,supplier:''}];
 const bills=[{id:id(701),number:'BB-000001',customer_id:customers[3].id,complaint_id:complaints[3].id,subtotal:450,service_charge:500,discount:0,gst_rate:0,gst_amount:0,total:950,created_at,idempotency_key:id(1701)}];
 const payments=[{id:id(702),bill_id:bills[0].id,amount:500,mode:'upi',created_at,idempotency_key:id(1702)}];
 const message_templates=['Diwali','Holi','Navratri','Eid','Raksha Bandhan','New Year','Summer AC service','Monsoon check-up','Service reminder'].map((name,i)=>({id:id(i+901),name,body:`Hi {name}, a ${name} update from {shop}. {offer} Call 7021935696 to book a service.`}));
 return {customers,complaints,bills,bill_items:[{id:id(703),bill_id:bills[0].id,name:'AC capacitor',quantity:1,unit_price:450}],payments,inventory_items,technicians:[{id:id(501),user_id:id(502),name:'Suresh Kumar',mobile:'9000000006',active:true}],warranties:[{id:id(401),complaint_id:complaints[3].id,customer_id:customers[3].id,appliance:'other',coverage:'Replaced parts',expires_at:addMonths(3)}],service_reminders:[{id:id(402),complaint_id:complaints[0].id,customer_id:customers[0].id,appliance:'ac',due_date:today(),done:false}],amc_plans:[],message_templates,campaigns:[],campaign_recipients:[],profiles:[{id:id(502),name:'Suresh Kumar',mobile:'9000000006',active:true}],user_roles:[{user_id:id(502),role:'technician'}],shop_settings:[defaults],complaint_status_history:complaints.map((c,i)=>({id:id(1001+i),complaint_id:c.id,status:c.status,actor_name:'Shop',created_at:c.created_at})),complaint_photos:[],expenses:[],feedback:[],stock_movements:[]};
}
export const emptyData=():Data=>Object.fromEntries(Object.keys(seed()).map(k=>[k,[]])) as Data;
