import {createContext,useContext,useState,useEffect,useCallback,useRef,ReactNode} from 'react';
import type {Data,Table,Tables,Line,Complaint} from '../types';import {useAuth} from './useAuth';import {demo,supabase} from '../lib/supabase';import {seed,emptyData} from '../lib/demo';import {totals,errorHindi} from '../lib/domain';
type State={data:Data;loading:boolean;error:string;notice:string;unread:number;sound:boolean;setSound:(v:boolean)=>void;clearUnread:()=>void;reload:()=>Promise<void>;notify:(s:string)=>void;mutate:<K extends Table>(t:K,v:Partial<Tables[K]>,id?:string|number)=>Promise<string>;rpc:(name:string,p:Record<string,unknown>)=>Promise<any>};
const Context=createContext<State>(null!);
export function DataProvider({children}:{children:ReactNode}){const {role,userId}=useAuth();const scope=useRef({role,userId});scope.current={role,userId};const [data,setData]=useState<Data>(()=>{if(demo){try{return JSON.parse(localStorage.getItem('balaji-demo-v1')??'null')??seed()}catch{return seed()}}return emptyData()}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[unread,setUnread]=useState(0),[sound,setSound]=useState(false);
 const notify=useCallback((s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),5000)},[]);
 const reload=useCallback(async()=>{if(demo||!supabase||!role)return;setLoading(true);setError('');try{
 const office=['customers','complaints','complaint_photos','complaint_status_history','technicians','bills','bill_items','payments','warranties','service_reminders','amc_plans','shop_settings','feedback'] as Table[];
 const owner=['inventory_items','stock_movements','expenses','message_templates','campaigns','campaign_recipients','profiles','user_roles'] as Table[];
 const tables:Table[]=role==='technician'?['complaints','complaint_photos','complaint_status_history','technicians']:role==='owner'?[...office,...owner]:office;
 const next=emptyData();await Promise.all(tables.map(async t=>{const all:any[]=[];for(let start=0;;start+=500){const {data:rows,error:e}=await supabase!.from(t).select('*').order(t==='user_roles'?'user_id':'id').range(start,start+499);if(e)throw e;all.push(...rows);if(rows.length<500)break;} (next[t] as any[])=all;}));
 if(role==='technician'){next.customers=await Promise.all(next.complaints.map(async j=>{const {data:c,error:e}=await supabase!.rpc('job_contact',{j:j.id});if(e)throw e;return {...c[0],id:j.customer_id,created_at:'',tags:[],whatsapp_opt_in:false,opt_out:false};}));}
 if(scope.current.role===role&&scope.current.userId===userId)setData(next);
 }catch(e){setError(errorHindi(e))}finally{setLoading(false)}},[role,userId]);
 useEffect(()=>{if(!role&&!demo)setData(emptyData());else void reload()},[role,reload]);
 useEffect(()=>{if(demo)localStorage.setItem('balaji-demo-v1',JSON.stringify(data))},[data]);
 useEffect(()=>{if(!supabase||demo||!role)return;const ch=supabase.channel('jobs').on('postgres_changes',{event:'INSERT',schema:'public',table:'complaints'},()=>{setUnread(x=>x+1);notify('New complaint received. Open Complaints to review it.');void reload();if(sound){try{const ctx=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();g.gain.value=.06;o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.16);o.onended=()=>void ctx.close();}catch{}}}).subscribe();return()=>{void supabase.removeChannel(ch)}},[role,reload,sound,notify]);
 async function mutate<K extends Table>(t:K,v:Partial<Tables[K]>,id?:string|number){if(!demo){if(!navigator.onLine)throw new Error('You are offline. Reconnect before saving.');if(!supabase)throw new Error('Supabase is not connected. Check the environment settings.');const q=id!==undefined?supabase.from(t).update(v).eq('id',id):supabase.from(t).insert(v);const {data:r,error:e}=await q.select().single();if(e)throw e;await reload();return String(r.id);}
 const newId=id??crypto.randomUUID();setData(prev=>{const rows=prev[t] as any[];return {...prev,[t]:id!==undefined?rows.map(r=>r.id===id?{...r,...v}:r):[...rows,{created_at:new Date().toISOString(),...v,id:newId}]}});return String(newId);}
 async function rpc(name:string,p:Record<string,any>){if(!demo){if(!navigator.onLine)throw new Error('You are offline. Reconnect before saving.');const {data:r,error:e}=await supabase!.rpc(name,p);if(e)throw e;await reload();return r;}
 const now=new Date().toISOString();let result:any=null;const next=structuredClone(data);
 if(name==='submit_admin_job'){const v=p.p;let c=next.customers.find(x=>x.mobile===v.mobile);if(!c){c={id:crypto.randomUUID(),name:v.name,mobile:v.mobile,address:v.address,tags:[],whatsapp_opt_in:!!v.whatsapp_opt_in,opt_out:false,created_at:now};next.customers.push(c);}else{c.name=v.name;c.address=v.address;}const j:Complaint={...v,id:crypto.randomUUID(),customer_id:c.id,number:`BE-${String(next.complaints.length+1).padStart(6,'0')}`,status:'pending',internal_notes:'',created_at:now,updated_at:now,feedback_token:crypto.randomUUID(),visit_at:v.visit_at||null,technician_id:v.technician_id||null};next.complaints.push(j);next.complaint_status_history.push({id:crypto.randomUUID(),complaint_id:j.id,status:j.status,actor_name:'Shop',created_at:now});result=j.id;}
 if(name==='update_job'){const j=next.complaints.find(x=>x.id===p.j)!;if(j.status!==p.s)next.complaint_status_history.push({id:crypto.randomUUID(),complaint_id:j.id,status:p.s,actor_name:role==='technician'?'Technician':'Shop',created_at:now});Object.assign(j,{status:p.s,internal_notes:p.n,updated_at:now},role==='technician'?{}:{technician_id:p.t,visit_at:p.v});}
 if(name==='save_bill'){const v=p.p;const existing=next.bills.find(b=>b.idempotency_key===v.idempotency_key);if(existing)return existing.id;const amount=totals(v.items,v.service_charge,v.discount,v.gst_rate);if(v.received>amount.total)throw new Error('The amount received exceeds the total. Check the amount.');const b={id:crypto.randomUUID(),number:`BB-${String(next.bills.length+1).padStart(6,'0')}`,customer_id:v.customer_id,complaint_id:v.complaint_id||null,subtotal:amount.subtotal,service_charge:v.service_charge,discount:v.discount,gst_rate:v.gst_rate,gst_amount:amount.tax,total:amount.total,created_at:now,idempotency_key:v.idempotency_key};
 for(const item of v.items as Line[]){if(item.inventory_id){const stock=next.inventory_items.find(x=>x.id===item.inventory_id);if(!stock||stock.stock_quantity<item.quantity)throw new Error('Not enough stock. Add stock first.');stock.stock_quantity-=item.quantity;next.stock_movements.push({id:crypto.randomUUID(),inventory_id:stock.id,bill_id:b.id,quantity:-item.quantity,reason:'Invoice usage',created_at:now});}next.bill_items.push({...item,id:crypto.randomUUID(),bill_id:b.id});}next.bills.push(b);if(v.received>0)next.payments.push({id:crypto.randomUUID(),bill_id:b.id,amount:v.received,mode:v.mode,created_at:now,idempotency_key:v.idempotency_key});result=b.id;}
 if(name==='add_payment'){const b=next.bills.find(x=>x.id===p.b)!;const paid=next.payments.filter(x=>x.bill_id===b.id).reduce((a,x)=>a+Number(x.amount),0);if(p.a<=0||p.a>b.total-paid)throw new Error('The payment exceeds the balance. Check the amount.');if(!next.payments.some(x=>x.idempotency_key===p.k))next.payments.push({id:crypto.randomUUID(),bill_id:b.id,amount:p.a,mode:p.m,created_at:now,idempotency_key:p.k});}
 if(name==='stock_adjust'){const i=next.inventory_items.find(x=>x.id===p.i)!;if(i.stock_quantity+p.q<0)throw new Error('Not enough stock. Reduce quantity.');i.stock_quantity+=p.q;next.stock_movements.push({id:crypto.randomUUID(),inventory_id:i.id,quantity:p.q,reason:p.r,created_at:now});}
 if(name==='archive_bill'){next.bills.find(x=>x.id===p.b)!.deleted_at=now;}
 setData(next);return result;}
 return <Context.Provider value={{data,loading,error,notice,unread,sound,setSound,clearUnread:()=>setUnread(0),reload,notify,mutate,rpc}}>{children}{notice&&<div role="status" className="toast">{notice}</div>}</Context.Provider>;
}
export const useData=()=>useContext(Context);
