import {useState,useEffect} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useData} from '../hooks/useData';import {useAuth} from '../hooks/useAuth';
import {PageTitle,Badge,Field,Empty,Editor,Skeleton} from '../components/common';
import {JobList} from '../components/JobList';import {ComplaintForm} from '../components/ComplaintForm';
import {Button} from '../components/ui/button';import {statusLabels,appliances,datetime,addMonths,wa,errorMessage,localDay,today} from '../lib/domain';
import {demo,supabase} from '../lib/supabase';import type {Status} from '../types';
export function Jobs(){const {data,loading}=useData(),{role,userId}=useAuth();const [status,setStatus]=useState(''),[q,setQ]=useState(''),[visits,setVisits]=useState(false);
 const jobs=data.complaints.filter(j=>(role!=='technician'||data.technicians.find(t=>t.id===j.technician_id)?.user_id===userId)&&(!status||j.status===status)&&(!visits||(j.visit_at&&localDay(new Date(j.visit_at))===today()))&&`${j.number} ${data.customers.find(c=>c.id===j.customer_id)?.name} ${data.customers.find(c=>c.id===j.customer_id)?.mobile}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 return <><PageTitle title={role==='technician'?'My jobs':'Complaints'} sub="Every repair, from first call to final check." action={role!=='technician'&&<Link to="/jobs/new" className="btn btn-primary">＋ New complaint</Link>}/><div className="toolbar"><input aria-label="Search complaints" placeholder="Name, mobile or complaint number…" value={q} onChange={e=>setQ(e.target.value)}/>{role==='technician'&&<Button variant="outline" onClick={()=>setVisits(!visits)}>{visits?'All assigned jobs':"Today's visits"}</Button>}</div><div className="toolbar"><button className={`chip ${!status?'selected':''}`} onClick={()=>setStatus('')}>All</button>{Object.entries(statusLabels).map(([s,l])=><button className={`chip ${status===s?'selected':''}`} key={s} onClick={()=>setStatus(s)}>{l}</button>)}</div><div className="card">{loading?<Skeleton/>:<JobList jobs={jobs}/>}</div></>;
}
export function NewJob(){return <><PageTitle title="New complaint" sub="Enter a mobile number to find an existing customer."/><ComplaintForm/></>}
function Photo({path}:{path:string}){const [url,setUrl]=useState(demo?path:'');useEffect(()=>{if(!demo&&supabase)supabase.storage.from('complaint-photos').createSignedUrl(path,3600).then(({data})=>setUrl(data?.signedUrl??''))},[path]);return url?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt="Repair photo"/></a>:<p className="muted">Loading photo…</p>}
export function JobDetail(){const {id}=useParams();const {data,rpc,mutate,notify,loading}=useData(),{role,userId}=useAuth();const j=data.complaints.find(j=>j.id===id);
 const [status,setStatus]=useState<Status>('pending'),[notes,setNotes]=useState(''),[tech,setTech]=useState(''),[visit,setVisit]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(j){setStatus(j.status);setNotes(j.internal_notes);setTech(j.technician_id??'');setVisit(j.visit_at?new Date(new Date(j.visit_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'')}},[j?.id,j?.updated_at]);
 if(loading&&!j)return <Skeleton/>;if(!j||(role==='technician'&&data.technicians.find(t=>t.id===j.technician_id)?.user_id!==userId))return <Empty title="Complaint unavailable" text="This job may not be assigned to your account."/>;
 const savedCustomer=data.customers.find(c=>c.id===j.customer_id)!;const c={...savedCustomer,name:j.reported_name??savedCustomer?.name,address:j.reported_address??savedCustomer?.address},settings=data.shop_settings[0],bills=data.bills.filter(b=>b.complaint_id===j.id&&!b.deleted_at),history=data.complaint_status_history.filter(h=>h.complaint_id===j.id).sort((a,b)=>a.created_at.localeCompare(b.created_at));
 async function save(){setBusy(true);setError('');try{await rpc('update_job',{j:j!.id,s:status,n:notes,t:tech||null,v:visit?new Date(visit).toISOString():null});notify('Status saved. You can now send an update on WhatsApp.');}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function upload(file:File,kind:string){setBusy(true);try{if(file.size>5242880||!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG or WebP under 5 MB.');let path='';if(demo)path=await new Promise<string>((r,fail)=>{const reader=new FileReader();reader.onload=()=>r(String(reader.result));reader.onerror=fail;reader.readAsDataURL(file)});else{path=`${j!.id}/${crypto.randomUUID()}.${file.type.split('/')[1]}`;const {error}=await supabase!.storage.from('complaint-photos').upload(path,file);if(error)throw error;}await mutate('complaint_photos',{complaint_id:j!.id,path,kind});notify('Photo saved.');}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <><PageTitle title={j.number} sub={`${appliances[j.appliance]} · ${datetime(j.created_at)}`} action={<Badge status={j.status}/>}/><div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 grid gap-5"><section className="card"><h2>{c?.name??'Customer'}</h2><p className="muted mt-2">{c?.address}</p><div className="toolbar"><a className="btn btn-outline" href={`tel:+91${c?.mobile}`}>Call · {c?.mobile}</a><a className="btn btn-outline" target="_blank" rel="noreferrer" href={wa(c?.mobile??'',`Hi ${c?.name}, complaint ${j.number} is now: ${statusLabels[j.status]}. — Balaji Electric`)}>WhatsApp update</a><a className="btn btn-outline" target="_blank" rel="noreferrer" href={'https:'+'//www.google.com/maps/search/?api=1&query='+encodeURIComponent(c?.address??'')}>Open in Maps</a></div><h3 className="mt-5">Reported issue</h3><p className="mt-2">{j.issue}</p><p className="muted text-sm mt-2">Brand / model: {j.brand||'Not provided'}</p></section>
 <section className="card"><h2>Status & work notes</h2><div className="form-grid mt-4"><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value as Status)}>{Object.entries(statusLabels).map(([s,l])=><option key={s} value={s}>{l}</option>)}</select></Field>{role!=='technician'&&<><Field label="Technician"><select value={tech} onChange={e=>setTech(e.target.value)}><option value="">Unassigned</option>{data.technicians.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Visit time"><input type="datetime-local" value={visit} onChange={e=>setVisit(e.target.value)}/></Field></>}<div className="col-span-full"><Field label="Internal notes"><textarea maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div>{error&&<p className="error col-span-full">{error}</p>}<Button disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save changes'}</Button></div></section>
 <section className="card"><h2>Repair photos</h2><div className="toolbar"><Field label="Before"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0],'before')}}/></Field><Field label="After"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0],'after')}}/></Field></div><div className="photo-grid">{data.complaint_photos.filter(p=>p.complaint_id===id).map(p=><div key={p.id}><Photo path={p.path}/><p className="muted text-sm mt-1">{p.kind==='before'?'Before':'After'}</p></div>)}</div></section>{role!=='technician'&&<section className="card"><h2>Bills & parts used</h2>{bills.map(b=><div key={b.id} className="my-3"><Link className="btn btn-outline" to={`/bills/${b.id}`}>{b.number}</Link><p className="mt-2 muted">{data.bill_items.filter(i=>i.bill_id===b.id).map(i=>`${i.name} × ${i.quantity}`).join(' · ')}</p></div>)}<Link className="btn btn-primary mt-4" to={`/bills/new?complaint=${id}`}>Create bill</Link></section>}</div>
 <div className="grid gap-5 content-start"><section className="card"><h2>Status timeline</h2><ul className="timeline">{history.map(h=><li key={h.id}><strong>{statusLabels[h.status]}</strong><p className="text-sm muted">{datetime(h.created_at)}</p><p className="text-sm muted">{h.actor_name}</p></li>)}</ul></section>{j.status==='completed'&&role!=='technician'&&<section className="card"><h2>After service</h2><div className="grid gap-3 mt-4"><Editor title="Set warranty" trigger="Set warranty" initial={{months:String(settings?.default_warranty??3),expires_at:addMonths(settings?.default_warranty??3),coverage:'Replaced parts only'}} fields={[{key:'months',label:'Duration',options:[{value:'0',label:'None'},{value:'1',label:'1 month'},{value:'3',label:'3 months'},{value:'6',label:'6 months'},{value:'12',label:'12 months'},{value:'custom',label:'Custom date'}]},{key:'expires_at',label:'Custom expiry date',type:'date'},{key:'coverage',label:'Coverage',required:true}]} onSave={async v=>{if(v.months==='0')return;const old=data.warranties.find(w=>w.complaint_id===j.id);await mutate('warranties',{complaint_id:j.id,customer_id:j.customer_id,appliance:j.appliance,coverage:v.coverage,expires_at:v.months&&v.months!=='custom'?addMonths(Number(v.months)):v.expires_at},old?.id)}}/>{j.appliance==='ac'&&<Editor title="Next service date" trigger="Set next service" initial={{due_date:addMonths(6)}} fields={[{key:'due_date',label:'Service due',type:'date',required:true}]} onSave={async v=>{await mutate('service_reminders',{complaint_id:j.id,customer_id:j.customer_id,appliance:'ac',due_date:v.due_date,done:false},data.service_reminders.find(r=>r.complaint_id===j.id)?.id)}}/>}<a className="btn btn-outline" target="_blank" rel="noreferrer" href={wa(c.mobile,`Hi ${c.name}, how was your repair? Rate our service: ${location.origin}/feedback/${j.feedback_token}${settings?.review_url?'\nGoogle review: '+settings.review_url:''}\nThank you — Balaji Electric`)}>Request a review</a></div></section>}</div></div></>;
}
