import {ReactNode,useState,FormEvent} from 'react';import {Button} from './ui/button';import {Dialog} from './ui/dialog';import {statusLabels,errorMessage} from '../lib/domain';import type {Status} from '../types';import {useData} from '../hooks/useData';
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Empty({title='Nothing here yet',text='Add a record to get started.',children}:{title?:string;text?:string;children?:ReactNode}){return <div className="empty"><div className="empty-mark">＋</div><h3>{title}</h3><p>{text}</p>{children}</div>}
export function Badge({status}:{status:Status}){return <span className={`badge ${status}`}>{statusLabels[status]}</span>}
export function PageTitle({title,sub,action}:{title:string;sub?:string;action?:ReactNode}){return <div className="page-title"><div><p className="eyebrow">BALAJI / SERVICE DESK</p><h1>{title}</h1>{sub&&<p className="muted">{sub}</p>}</div>{action}</div>}
export function Skeleton(){return <div className="grid gap-4" aria-label="Loading records">{[1,2,3].map(i=><div key={i} className="skeleton"/>)}</div>}
export type FormField={key:string;label:string;type?:string;options?:{value:string;label:string}[];required?:boolean};
export function Editor({title,initial,fields,onSave,trigger='Add'}:{title:string;initial?:Record<string,any>;fields:FormField[];onSave:(p:Record<string,any>)=>Promise<void>;trigger?:string}){const [open,setOpen]=useState(false),[v,setV]=useState<Record<string,any>>(initial??{}),[busy,setBusy]=useState(false),[error,setError]=useState('');const {notify}=useData();async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await onSave(v);setOpen(false);notify('Saved successfully.');}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}return <><Button onClick={()=>{setV(initial??{});setError('');setOpen(true)}} variant="outline">{trigger}</Button><Dialog open={open} onOpenChange={setOpen} title={title}><form onSubmit={submit} className="form-grid mt-4">{fields.map(f=><Field key={f.key} label={f.label}>{f.options?<select required={f.required} value={v[f.key]??''} onChange={e=>setV({...v,[f.key]:e.target.value})}><option value="">Select…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='checkbox'?<input type="checkbox" checked={!!v[f.key]} onChange={e=>setV({...v,[f.key]:e.target.checked})}/>:f.type==='textarea'?<textarea required={f.required} value={v[f.key]??''} onChange={e=>setV({...v,[f.key]:e.target.value})}/>:<input required={f.required} type={f.type??'text'} min={f.type==='number'?0:undefined} step={f.type==='number'?'0.01':undefined} value={v[f.key]??''} onChange={e=>setV({...v,[f.key]:f.type==='number'?Number(e.target.value):e.target.value})}/>}</Field>)}{error&&<p role="alert" className="error col-span-full">{error}</p>}<Button type="submit" className="col-span-full" disabled={busy}>{busy?'Saving…':'Save changes'}</Button></form></Dialog></>}
export function Confirm({label,title,onConfirm}:{label:string;title:string;onConfirm:()=>Promise<void>}){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');return <><Button variant="ghost" onClick={()=>setOpen(true)}>{label}</Button><Dialog open={open} onOpenChange={setOpen} title={title}><p className="my-4">The record will be archived, not permanently deleted. Continue?</p>{error&&<p className="error">{error}</p>}<Button variant="destructive" disabled={busy} onClick={async()=>{setBusy(true);try{await onConfirm();setOpen(false)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}}>{busy?'Saving…':'Yes, archive'}</Button></Dialog></>}
